### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by seema84** [RobiFox/BlockQuest#3]
First thanks for this great plugin.

I have some suggestions:
1. add a permission for player (blockquest.use)
2. add a admin command for stats
3. remove the two reload messages (every owner know this)
4. find a solution if a inventory is full
5. soon

**Comment by RobiFox** [comment]
Hi there,
Here are my responses for your ideas in order:

- What do you mean by this? Requiring permissions, for finding blocks?
- Will do this.
- Actually, not everyone. People were complaining before that reload messed up stats.
- Not sure how would this fit in the plugin

Thanks.

**Comment by seema84** [comment]
"Requiring permissions, for finding blocks?"
Yes

"Will do this."
sounds good

"Actually, not everyone."
If all would do it would be a massiv spam. Spigot has a own reload warning message. Its really superfluous.

"Not sure how would this fit in the plugin"
its not hard to do this. if player found the "last" Block "and" the inventory is full, send a message (please clear your inventory) and do not set this Block as found.

**Comment by RobiFox** [comment]
Not sure about the first one, and I don't plan on removing the reload message.
It doesn't print it in the console, and you can only see it if it's reloaded.
Other 2 suggestion will be added, and will be closed when implemented.

**Comment by seema84** [comment]
"Not sure about the first one"
why? if i add some blocks to blockquest, player can start befor i finish to add all blocks. with a permission its easy to handle.

"I don't plan on removing"
why? i know no plugin to do this. what is so special about this plugin?
would all plugins send this messages i would get every restart 100 reload warning messages
and no this message also appears on server stop

**Comment by RobiFox** [comment]
If that's the case, I can do that.

As for reload, when the server stops, chat gets cleared anyways.
I can move it to the reload command though, this just seemed easier.
Reloading messes up stats, so all blocks become available to be found again.

**Comment by RobiFox** [comment]
Suggestions added in 1.6.

**Comment by seema84** [comment]
thanks for this update.

a problem with your full inventory solution, when i give a player 2 or more items and he has only one free slot than he get only the first of all items

**Comment by RobiFox** [comment]
Will do once I'll have time.

**Comment by RobiFox** [comment]
Added in 1.6.1.
