### ISSUE TITLE
[REQUEST] Multiple BlockQuest Series

### ISSUE THREAD

**Issue by Flavourized** [RobiFox/BlockQuest#4]
Since I was called out in the plugin discussion, I figured I should show some effort! Also because you said this was planned in a future update. Something that has been requested by multiple people is the ability to make multiple block series.

 For example, our server has 7 "Easter Eggs" in our spawn city, players find these easter eggs and get a prize. However, come some special time of the year, we like to theme our spawn city, and make a scavenger hunt that is relevant for the event. So this halloween, we made a 50 block scavenger hunt, but had to completely disable the 7 Easter Eggs. 

0.) First and foremost, with the addition of features, there should also be a way to edit plugin locale, messages produced by the plugin (which you have done since the start)

0.5) Save block locations for a series in its own file. Config.yml for settings, blocks.yml for storing series data, and users.yml (or w/e you currently have to store player data). 

1.)  I would like to have would be the ability to enable or disable any block series with a command **/blockquest toggle {seriesName}**. This would mean that if a block series is DISABLED, players who click a block from this series would receive a message saying "This series is disabled".

2.) Make the block editor a little more smooth. When I was making the 50 block scavenger hunt with this plugin, I had to place the block, open chatbox & type /blockquest, and right-click the block. Maybe have a command where **/blockquest edit {seriesName}** gives you a tool, like a stick with a certain name or lore, and with that tool you can can simply left-click to add a block to the series, and right-click to remove the block from the series. There should be messages sent to the player saying "Added block to {seriesName}" or "Removed block from {SeriesName}"

2.5) To make 1) and 2) work together and to iron out multiple series, make a create command. So we would have something like **/blockquest create {seriesName}** which will make a spot in the blocks.yml as well as give the player the BlockQuest editing tool from 2). Then every 

3) Permission based series. With multiple series, add the ability to have permissions per series. Node could be blockquest.quest.{seriesName}. The player or group would need to have this permission to be able to collect blocks for this series. 

4) A personal stats command, maybe **/blockquest stats <user>**. If <user> argument is missing, just show the stats of the player who typed the command. Output could be:
{player}'s BlockQuest Stats
{seriesName1}:
  Found Blocks: 45
  Blocks Left: 5
{seriesName2}:
  FoundBlocks: 0
  Blocks Left: 7

5) For admins, a series info command, maybe **/blockquest info {seriesName}**, could be:
{seriesName} Information
  Total Blocks: 50

5.5) Following the same idea as 5), a command to teleport to a block in the series, maybe **/blockquest teleport {seriesName} {blockNum}**

6) This one is not even a little bit necessary, but would allow us admins to do something extra, but adding a command where we can set a blockquest block for a series with a location. The command could be /blockquest setblock {seriesName} {LocX} {LocY} {LocZ} which would set a block in series {seriesName} at location {LocX} {LocY} {LocZ}. In this command, if the series does not exist, create it. The admin will still need to add the permission node for this series to player groups. 

Anyways, just a few ideas. Thanks for reading :)

**Comment by Flavourized** [comment]
Oh, another possible idea would be to add integration with HolographicDisplays, that way we could make holograms as the block instead of physical blocks. Should obviously be a soft dependencey

**Comment by Flavourized** [comment]
another idea is adding a command that will reset a player's data for the specific series. Command could be /blockquest reset {player} {seriesName}

This command would remove the player's data for that series, as if the player never got those blocks. 

Alternatively, add a command that will complete a series, as if the player had gotten all the blocks in the series. Command could be /blockquest complete {player} {seriesName}

**Comment by RobiFox** [comment]
The multi-block feature is planned (as said), however I don't have the best solution do it, without rewriting most of the code.
Suggestions noted.

**Comment by Flavourized** [comment]
Isn't that always the start of a v2.0.0? :)

**Comment by Flavourized** [comment]
Any chance of a release for this december? Would love to implement the new version for the upcoming holidays :D

**Comment by RobiFox** [comment]
Doubt, sorry.
You can, however, do this with current version.
All you have to do is duplicate BlockQuest.jar, extract it's plugin.yml, change "name:" to something, like BlockQuest2, and you can access both using /blockquest2:blockquest and /blockquest:blockquest
But however, **this is not an official solution.**

**Comment by RobiFox** [comment]
Hey,
Since Update 2.0 is out now, where serieses are now a thing, I think it's safe to close this thread.
I'll answer the requests:

0) The only message that a normal player can see, is the no permission message, so in 2.0 that's the only changeable message. I don't see any reason why others should be changeable, but if you have a reason, please open a new issue, or PM me somewhere, and I'll consider it

0.5) Blocks in 2.0 are stored in one file, because it'd be a bit complex for me to store each of them in its own file. I might revisit this idea later.

1) It's now possible

2) The way to add blocks has stood the same, I am not sure how would I do the item. I might revisit this idea later.

3) I will consider this.

5.5) This is now possible in 2.0

6) I don't think this will make it into the plugin, because I don't really see a point in it. If you knew the coordinates, you could've added the blocks already.

Thank you for your patience and sorry for keeping you waiting.
