### ISSUE TITLE
[BUG] Ghetto multi-series system. 

### ISSUE THREAD

**Issue by Flavourized** [RobiFox/BlockQuest#5]
Hey, so i wanted to put my experience with multiple series blockquests here. 

Currently BlockQuest saved all series blocks in the config.yml, and saves player data in data.yml. We have a set of 7 blocks that we keep year-round except for special holidays like halloween. For halloween, i decided to add a 50 block blockquest. 

So this is what i did:
1) Removed the 7 existing blocks
2) Reloaded blockquest
3) Set my 50 blocks (and assign them to blockquest)
4) Reload blockquest
5) Change current data.yml to OLDdata.yml
6) Reload blockquest
7) /blockquest toggle
8) let blockquest create another data.yml

So what went wrong: some players somehow still had the data from the 7 blocks before, assigned to their UUID. So when they clicked their  first block for the 50 blockquest hunt, the plugin returned "42 left". If they found these 42 blocks, they would get the reward for the 50 blockquest hunt, but if they found additional blocks after this, (7 extra) they would get the All-blocks-found completion reward. 

Just thought i would put that here.

**Comment by RobiFox** [comment]
Make sure to stop the server, and then delete data.yml.
Let me know if it has been resolved.

**Comment by RobiFox** [comment]
Closed due to no feedback in 2 days.
