### ISSUE TITLE
armorstand visible

### ISSUE THREAD

**Issue by seema84** [RobiFox/BlockQuest#6]
sometime i can show for a short while the armorstand befor it will invisble

config setting:
invisible: true

**Comment by RobiFox** [comment]
Hey,
Sorry for the late answer.
I just recently got back to developing plugins.
I'm currently recoding the plugin. Maybe we should see if it's fixed in 2.0?

**Comment by RobiFox** [comment]
Hey,
Since 2.0 is released (but sadly no find effects yet), I'll go ahead and close this thread.
If find effect is back, and so is this issue, please open a new issue.

Thank you.

**Comment by seema84** [comment]
okay thanks
